// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WithTool_slugPostRequestBody_custom_connection_dataMember5_authScheme
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BASIC")]
        #pragma warning disable CS1591
        BASIC,
        #pragma warning restore CS1591
    }
}
