// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item.Link
{
    /// <summary>Sharing model for this connected account. PRIVATE (default) is usable only by the owning user_id. SHARED is reachable from a tool-router session ONLY when explicitly pinned in the session config — at most one SHARED connection per toolkit per session. Sessions never use a SHARED connection implicitly. Set at creation time only — cannot be changed later.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LinkPostRequestBody_account_type
    {
        [EnumMember(Value = "PRIVATE")]
        #pragma warning disable CS1591
        PRIVATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SHARED")]
        #pragma warning disable CS1591
        SHARED,
        #pragma warning restore CS1591
    }
}
