// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DefaultAuthConfigUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether this auth config is enabled for tool router</summary>
        public bool? IsEnabledForToolRouter { get; set; }
        /// <summary>The display name of the authentication configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Use tool_access_config instead. This field will be deprecated in the future.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RestrictToFollowingTools { get; set; }
#nullable restore
#else
        public List<string> RestrictToFollowingTools { get; set; }
#endif
        /// <summary>OAuth scopes requested for the auth config.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateScopes? Scopes { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateScopes Scopes { get; set; }
#endif
        /// <summary>Shared credentials inherited by all connected accounts using this auth config. Secret values are redacted in responses, so provide the real values when updating; omit this field to leave them unchanged.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateSharedCredentialsProperty? SharedCredentials { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateSharedCredentialsProperty SharedCredentials { get; set; }
#endif
        /// <summary>The tool_access_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateToolAccessConfig? ToolAccessConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateToolAccessConfig ToolAccessConfig { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultValueType? Type { get; set; }
        /// <summary>OAuth user-token scopes requested for the auth config. This is primarily used by Slack OAuth v2.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateUserScopes? UserScopes { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateUserScopes UserScopes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate"/> and sets the default values.
        /// </summary>
        public DefaultAuthConfigUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is_enabled_for_tool_router", n => { IsEnabledForToolRouter = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "restrict_to_following_tools", n => { RestrictToFollowingTools = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "scopes", n => { Scopes = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateScopes>(global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateScopes.CreateFromDiscriminatorValue); } },
                { "shared_credentials", n => { SharedCredentials = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateSharedCredentialsProperty>(global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateSharedCredentialsProperty.CreateFromDiscriminatorValue); } },
                { "tool_access_config", n => { ToolAccessConfig = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateToolAccessConfig>(global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateToolAccessConfig.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultValueType>(); } },
                { "user_scopes", n => { UserScopes = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateUserScopes>(global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateUserScopes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is_enabled_for_tool_router", IsEnabledForToolRouter);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("restrict_to_following_tools", RestrictToFollowingTools);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateScopes>("scopes", Scopes);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateSharedCredentialsProperty>("shared_credentials", SharedCredentials);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateToolAccessConfig>("tool_access_config", ToolAccessConfig);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultValueType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdateUserScopes>("user_scopes", UserScopes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
