// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>Current status of the authentication configuration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetAuthConfigsByNanoid200ResponseStatus
    {
        [EnumMember(Value = "ENABLED")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLED")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
