// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetConnectedAccountsByNanoid200_stateMember12_authScheme
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SAML")]
        #pragma warning disable CS1591
        SAML,
        #pragma warning restore CS1591
    }
}
