// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchAuthConfigsByNanoidRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate? CustomAuthConfigUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate CustomAuthConfigUpdate { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate? DefaultAuthConfigUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate DefaultAuthConfigUpdate { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PatchAuthConfigsByNanoidRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.PatchAuthConfigsByNanoidRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Composio.OpenApiClient.Models.PatchAuthConfigsByNanoidRequest();
            if("custom".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomAuthConfigUpdate = new global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate();
            }
            else if("default".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DefaultAuthConfigUpdate = new global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomAuthConfigUpdate != null)
            {
                return CustomAuthConfigUpdate.GetFieldDeserializers();
            }
            else if(DefaultAuthConfigUpdate != null)
            {
                return DefaultAuthConfigUpdate.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomAuthConfigUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.CustomAuthConfigUpdate>(null, CustomAuthConfigUpdate);
            }
            else if(DefaultAuthConfigUpdate != null)
            {
                writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.DefaultAuthConfigUpdate>(null, DefaultAuthConfigUpdate);
            }
        }
    }
}
#pragma warning restore CS0618
