// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>The auth scheme of the connected account. Must match the connection&apos;s actual auth scheme.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatchConnectedAccountBody_connection_state_authScheme
    {
        [EnumMember(Value = "BEARER_TOKEN")]
        #pragma warning disable CS1591
        BEARER_TOKEN,
        #pragma warning restore CS1591
        [EnumMember(Value = "API_KEY")]
        #pragma warning disable CS1591
        API_KEY,
        #pragma warning restore CS1591
        [EnumMember(Value = "BASIC")]
        #pragma warning disable CS1591
        BASIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "BASIC_WITH_JWT")]
        #pragma warning disable CS1591
        BASIC_WITH_JWT,
        #pragma warning restore CS1591
        [EnumMember(Value = "GOOGLE_SERVICE_ACCOUNT")]
        #pragma warning disable CS1591
        GOOGLE_SERVICE_ACCOUNT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SERVICE_ACCOUNT")]
        #pragma warning disable CS1591
        SERVICE_ACCOUNT,
        #pragma warning restore CS1591
    }
}
