// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostConnectedAccounts201Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The connection data of the connected account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseConnectionData? ConnectionData { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseConnectionData ConnectionData { get; set; }
#endif
        /// <summary>&quot;DEPRECATED: This field will be removed in a future version. Please use id and auth_config.id instead.&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseDeprecated? Deprecated { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseDeprecated Deprecated { get; set; }
#endif
        /// <summary>Experimental features - not stable, may be modified or removed in future versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseExperimental? Experimental { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseExperimental Experimental { get; set; }
#endif
        /// <summary>The id of the connected account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>&quot;DEPRECATED: This field will be removed in a future version&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUri { get; set; }
#nullable restore
#else
        public string RedirectUri { get; set; }
#endif
        /// <summary>&quot;DEPRECATED: This field will be removed in a future version&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUrl { get; set; }
#nullable restore
#else
        public string RedirectUrl { get; set; }
#endif
        /// <summary>&quot;DEPRECATED: This field will be removed in a future version&quot;</summary>
        [Obsolete("")]
        public global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201Response"/> and sets the default values.
        /// </summary>
        public PostConnectedAccounts201Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connectionData", n => { ConnectionData = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseConnectionData>(global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseConnectionData.CreateFromDiscriminatorValue); } },
                { "deprecated", n => { Deprecated = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseDeprecated>(global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseDeprecated.CreateFromDiscriminatorValue); } },
                { "experimental", n => { Experimental = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseExperimental>(global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseExperimental.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "redirect_uri", n => { RedirectUri = n.GetStringValue(); } },
                { "redirect_url", n => { RedirectUrl = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseConnectionData>("connectionData", ConnectionData);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseDeprecated>("deprecated", Deprecated);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseExperimental>("experimental", Experimental);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("redirect_uri", RedirectUri);
            writer.WriteStringValue("redirect_url", RedirectUrl);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostConnectedAccounts201ResponseStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
