// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>When &quot;required&quot;, the agent must specify which account to use. Present only when multiple accounts exist.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostToolRouterSessionBySessionIdSearch200_toolkit_connection_statuses_account_selection
    {
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
    }
}
