// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>Search path to use. Defaults to auto. Use tool_search to bypass cached plans and run direct tool search.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostToolRouterSessionBySessionIdSearchRequestSearchStrategy
    {
        [EnumMember(Value = "auto")]
        #pragma warning disable CS1591
        Auto,
        #pragma warning restore CS1591
        [EnumMember(Value = "tool_search")]
        #pragma warning disable CS1591
        ToolSearch,
        #pragma warning restore CS1591
    }
}
