// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    /// <summary>The unique slug identifier of the meta tool to execute</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostToolRouterSessionBySessionIdExecuteMetaRequestSlug
    {
        [EnumMember(Value = "COMPOSIO_SEARCH_TOOLS")]
        #pragma warning disable CS1591
        ComposioSearchTools,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_MULTI_EXECUTE_TOOL")]
        #pragma warning disable CS1591
        ComposioMultiExecuteTool,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_MANAGE_CONNECTIONS")]
        #pragma warning disable CS1591
        ComposioManageConnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_WAIT_FOR_CONNECTIONS")]
        #pragma warning disable CS1591
        ComposioWaitForConnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_REMOTE_WORKBENCH")]
        #pragma warning disable CS1591
        ComposioRemoteWorkbench,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_REMOTE_BASH_TOOL")]
        #pragma warning disable CS1591
        ComposioRemoteBashTool,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_GET_TOOL_SCHEMAS")]
        #pragma warning disable CS1591
        ComposioGetToolSchemas,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_UPSERT_RECIPE")]
        #pragma warning disable CS1591
        ComposioUpsertRecipe,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPOSIO_GET_RECIPE")]
        #pragma warning disable CS1591
        ComposioGetRecipe,
        #pragma warning restore CS1591
    }
}
