// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostToolRouterSessionBySessionIdProxyExecute_custom_connection_dataMember6_authScheme
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BEARER_TOKEN")]
        #pragma warning disable CS1591
        BEARER_TOKEN,
        #pragma warning restore CS1591
    }
}
