// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostAuthConfigsRequestAuthConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authScheme property</summary>
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigAuthScheme? AuthScheme { get; set; }
        /// <summary>The credentials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigCredentials? Credentials { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigCredentials Credentials { get; set; }
#endif
        /// <summary>Whether this auth config is enabled for tool router</summary>
        public bool? IsEnabledForToolRouter { get; set; }
        /// <summary>The name of the integration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The proxy_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigProxyConfig? ProxyConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigProxyConfig ProxyConfig { get; set; }
#endif
        /// <summary>Use tool_access_config instead. This field will be deprecated in the future.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RestrictToFollowingTools { get; set; }
#nullable restore
#else
        public List<string> RestrictToFollowingTools { get; set; }
#endif
        /// <summary>[EXPERIMENTAL] Shared credentials that will be inherited by all connected accounts using this auth config</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigSharedCredentials? SharedCredentials { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigSharedCredentials SharedCredentials { get; set; }
#endif
        /// <summary>The tool_access_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigToolAccessConfig? ToolAccessConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigToolAccessConfig ToolAccessConfig { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfig"/> and sets the default values.
        /// </summary>
        public PostAuthConfigsRequestAuthConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authScheme", n => { AuthScheme = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigAuthScheme>(); } },
                { "credentials", n => { Credentials = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigCredentials>(global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigCredentials.CreateFromDiscriminatorValue); } },
                { "is_enabled_for_tool_router", n => { IsEnabledForToolRouter = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "proxy_config", n => { ProxyConfig = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigProxyConfig>(global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigProxyConfig.CreateFromDiscriminatorValue); } },
                { "restrict_to_following_tools", n => { RestrictToFollowingTools = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "shared_credentials", n => { SharedCredentials = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigSharedCredentials>(global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigSharedCredentials.CreateFromDiscriminatorValue); } },
                { "tool_access_config", n => { ToolAccessConfig = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigToolAccessConfig>(global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigToolAccessConfig.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigAuthScheme>("authScheme", AuthScheme);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigCredentials>("credentials", Credentials);
            writer.WriteBoolValue("is_enabled_for_tool_router", IsEnabledForToolRouter);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigProxyConfig>("proxy_config", ProxyConfig);
            writer.WriteCollectionOfPrimitiveValues<string>("restrict_to_following_tools", RestrictToFollowingTools);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigSharedCredentials>("shared_credentials", SharedCredentials);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigToolAccessConfig>("tool_access_config", ToolAccessConfig);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostAuthConfigsRequestAuthConfigType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
