// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PostToolsExecuteProxy : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Binary body to send. For binary upload via URL: use {url: \&quot;https://...\&quot;, content_type?: \&quot;...\&quot;}. For binary upload via base64: use {base64: \&quot;...\&quot;, content_type?: \&quot;...\&quot;}.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body? BinaryBody { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body BinaryBody { get; set; }
#endif
        /// <summary>The request body (for POST, PUT, and PATCH requests)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Body { get; set; }
#nullable restore
#else
        public UntypedNode Body { get; set; }
#endif
        /// <summary>The ID of the connected account to use for authentication (if not provided, will use the default account for the project)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectedAccountId { get; set; }
#nullable restore
#else
        public string ConnectedAccountId { get; set; }
#endif
        /// <summary>The custom_connection_data property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data? CustomConnectionData { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data CustomConnectionData { get; set; }
#endif
        /// <summary>The API endpoint to call (absolute URL or path relative to base URL of the connected account)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Endpoint { get; set; }
#nullable restore
#else
        public string Endpoint { get; set; }
#endif
        /// <summary>The HTTP method to use for the request</summary>
        public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_method? Method { get; set; }
        /// <summary>Additional HTTP headers or query parameters to include in the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_parameters>? Parameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_parameters> Parameters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy"/> and sets the default values.
        /// </summary>
        public PostToolsExecuteProxy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "binary_body", n => { BinaryBody = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body>(global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body.CreateFromDiscriminatorValue); } },
                { "body", n => { Body = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "connected_account_id", n => { ConnectedAccountId = n.GetStringValue(); } },
                { "custom_connection_data", n => { CustomConnectionData = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data>(global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data.CreateFromDiscriminatorValue); } },
                { "endpoint", n => { Endpoint = n.GetStringValue(); } },
                { "method", n => { Method = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_method>(); } },
                { "parameters", n => { Parameters = n.GetCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_parameters>(global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_parameters.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body>("binary_body", BinaryBody);
            writer.WriteObjectValue<UntypedNode>("body", Body);
            writer.WriteStringValue("connected_account_id", ConnectedAccountId);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data>("custom_connection_data", CustomConnectionData);
            writer.WriteStringValue("endpoint", Endpoint);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_method>("method", Method);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_parameters>("parameters", Parameters);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PostToolsExecuteProxy_binary_body : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1? PostToolsExecuteProxyBinaryBodyMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1 PostToolsExecuteProxyBinaryBodyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember2? PostToolsExecuteProxyBinaryBodyMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember2 PostToolsExecuteProxyBinaryBodyMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_binary_body();
                result.PostToolsExecuteProxyBinaryBodyMember1 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1();
                result.PostToolsExecuteProxyBinaryBodyMember2 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember2();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PostToolsExecuteProxyBinaryBodyMember1 != null || PostToolsExecuteProxyBinaryBodyMember2 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PostToolsExecuteProxyBinaryBodyMember1, PostToolsExecuteProxyBinaryBodyMember2);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_binary_bodyMember1>(null, PostToolsExecuteProxyBinaryBodyMember1, PostToolsExecuteProxyBinaryBodyMember2);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PostToolsExecuteProxy_custom_connection_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1? PostToolsExecuteProxyCustomConnectionDataMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1 PostToolsExecuteProxyCustomConnectionDataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10? PostToolsExecuteProxyCustomConnectionDataMember10 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10 PostToolsExecuteProxyCustomConnectionDataMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11? PostToolsExecuteProxyCustomConnectionDataMember11 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11 PostToolsExecuteProxyCustomConnectionDataMember11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2? PostToolsExecuteProxyCustomConnectionDataMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2 PostToolsExecuteProxyCustomConnectionDataMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3? PostToolsExecuteProxyCustomConnectionDataMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3 PostToolsExecuteProxyCustomConnectionDataMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4? PostToolsExecuteProxyCustomConnectionDataMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4 PostToolsExecuteProxyCustomConnectionDataMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5? PostToolsExecuteProxyCustomConnectionDataMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5 PostToolsExecuteProxyCustomConnectionDataMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6? PostToolsExecuteProxyCustomConnectionDataMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6 PostToolsExecuteProxyCustomConnectionDataMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7? PostToolsExecuteProxyCustomConnectionDataMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7 PostToolsExecuteProxyCustomConnectionDataMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8? PostToolsExecuteProxyCustomConnectionDataMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8 PostToolsExecuteProxyCustomConnectionDataMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9? PostToolsExecuteProxyCustomConnectionDataMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9 PostToolsExecuteProxyCustomConnectionDataMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy.PostToolsExecuteProxy_custom_connection_data();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember1 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember10 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember11 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember2 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember3 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember4 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember5 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember6 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember7 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember8 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PostToolsExecuteProxyCustomConnectionDataMember9 = new global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PostToolsExecuteProxyCustomConnectionDataMember1 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember1.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember10 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember10.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember11 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember11.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember2 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember2.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember3 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember3.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember4 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember4.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember5 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember5.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember6 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember6.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember7 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember7.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember8 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember8.GetFieldDeserializers();
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember9 != null)
                {
                    return PostToolsExecuteProxyCustomConnectionDataMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(PostToolsExecuteProxyCustomConnectionDataMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember1>(null, PostToolsExecuteProxyCustomConnectionDataMember1);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember10 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember10>(null, PostToolsExecuteProxyCustomConnectionDataMember10);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember11>(null, PostToolsExecuteProxyCustomConnectionDataMember11);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember2>(null, PostToolsExecuteProxyCustomConnectionDataMember2);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember3>(null, PostToolsExecuteProxyCustomConnectionDataMember3);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember4>(null, PostToolsExecuteProxyCustomConnectionDataMember4);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember5>(null, PostToolsExecuteProxyCustomConnectionDataMember5);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember6>(null, PostToolsExecuteProxyCustomConnectionDataMember6);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember7>(null, PostToolsExecuteProxyCustomConnectionDataMember7);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember8>(null, PostToolsExecuteProxyCustomConnectionDataMember8);
                }
                else if(PostToolsExecuteProxyCustomConnectionDataMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.PostToolsExecuteProxy_custom_connection_dataMember9>(null, PostToolsExecuteProxyCustomConnectionDataMember9);
                }
            }
        }
    }
}
#pragma warning restore CS0618
