// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProxyExecuteCompleted : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Binary body response data. Present when the response is a binary file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedBinaryData? BinaryData { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedBinaryData BinaryData { get; set; }
#endif
        /// <summary>The response data returned from the proxied API</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedData? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedData Data { get; set; }
#endif
        /// <summary>The HTTP headers returned from the proxied API</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedHeadersProperty? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedHeadersProperty Headers { get; set; }
#endif
        /// <summary>The tool ran and succeeded</summary>
        public global::Soenneker.Composio.OpenApiClient.Models.CompletedResultType? ResultType { get; set; }
        /// <summary>The HTTP status code returned from the proxied API</summary>
        public double? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompleted"/> and sets the default values.
        /// </summary>
        public ProxyExecuteCompleted()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompleted"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompleted CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompleted();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "binary_data", n => { BinaryData = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedBinaryData>(global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedBinaryData.CreateFromDiscriminatorValue); } },
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedData>(global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedData.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedHeadersProperty>(global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedHeadersProperty.CreateFromDiscriminatorValue); } },
                { "result_type", n => { ResultType = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Models.CompletedResultType>(); } },
                { "status", n => { Status = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedBinaryData>("binary_data", BinaryData);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedData>("data", Data);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ProxyExecuteCompletedHeadersProperty>("headers", Headers);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Models.CompletedResultType>("result_type", ResultType);
            writer.WriteDoubleValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
