// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ToolRouterToolkitsListResponse_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Available Composio-managed auth schemes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ComposioManagedAuthSchemes { get; set; }
#nullable restore
#else
        public List<string> ComposioManagedAuthSchemes { get; set; }
#endif
        /// <summary>Connected account if available</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_connected_account? ConnectedAccount { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_connected_account ConnectedAccount { get; set; }
#endif
        /// <summary>Whether the toolkit is enabled</summary>
        public bool? Enabled { get; set; }
        /// <summary>Whether the toolkit is no-auth</summary>
        public bool? IsNoAuth { get; set; }
        /// <summary>Toolkit metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_meta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_meta Meta { get; set; }
#endif
        /// <summary>Display name of the toolkit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Unique slug identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items"/> and sets the default values.
        /// </summary>
        public ToolRouterToolkitsListResponse_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "composio_managed_auth_schemes", n => { ComposioManagedAuthSchemes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "connected_account", n => { ConnectedAccount = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_connected_account>(global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_connected_account.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "is_no_auth", n => { IsNoAuth = n.GetBoolValue(); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_meta>(global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_meta.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("composio_managed_auth_schemes", ComposioManagedAuthSchemes);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_connected_account>("connected_account", ConnectedAccount);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("is_no_auth", IsNoAuth);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolRouterToolkitsListResponse_items_meta>("meta", Meta);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("slug", Slug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
