// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ToolDetails : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of all available versions for this tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AvailableVersions { get; set; }
#nullable restore
#else
        public List<string> AvailableVersions { get; set; }
#endif
        /// <summary>The deprecated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsDeprecated? Deprecated { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsDeprecated Deprecated { get; set; }
#endif
        /// <summary>Detailed explanation of the tool&apos;s functionality and purpose</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Human-friendly description of the tool, if available</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HumanDescription { get; set; }
#nullable restore
#else
        public string HumanDescription { get; set; }
#endif
        /// <summary>Schema definition of required input parameters for the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsInputParametersProperty? InputParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsInputParametersProperty InputParameters { get; set; }
#endif
        /// <summary>Present only when the tool supports an Instant account and its selected toolkit version is the latest. Missing for older toolkit versions or ineligible tools.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.InstantAccount? Instant { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.InstantAccount Instant { get; set; }
#endif
        /// <summary>Indicates if this tool is deprecated and may be removed in the future</summary>
        public bool? IsDeprecated { get; set; }
        /// <summary>Human-readable display name of the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates if the tool can be used without authentication</summary>
        public bool? NoAuth { get; set; }
        /// <summary>Schema definition of return values from the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsOutputParametersProperty? OutputParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsOutputParametersProperty OutputParameters { get; set; }
#endif
        /// <summary>Structured scope requirements for the tool. Null means the tool is legacy and only exposes flat scopes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsScopeRequirements? ScopeRequirements { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsScopeRequirements ScopeRequirements { get; set; }
#endif
        /// <summary>List of scopes associated with the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scopes { get; set; }
#nullable restore
#else
        public List<string> Scopes { get; set; }
#endif
        /// <summary>Unique identifier for the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>List of tags associated with the tool for categorization and filtering</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The toolkit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsToolkit? Toolkit { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsToolkit Toolkit { get; set; }
#endif
        /// <summary>Current version of the tool</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Models.ToolDetails"/> and sets the default values.
        /// </summary>
        public ToolDetails()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Models.ToolDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Models.ToolDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Models.ToolDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "available_versions", n => { AvailableVersions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "deprecated", n => { Deprecated = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsDeprecated>(global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsDeprecated.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "human_description", n => { HumanDescription = n.GetStringValue(); } },
                { "input_parameters", n => { InputParameters = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsInputParametersProperty>(global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsInputParametersProperty.CreateFromDiscriminatorValue); } },
                { "instant", n => { Instant = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.InstantAccount>(global::Soenneker.Composio.OpenApiClient.Models.InstantAccount.CreateFromDiscriminatorValue); } },
                { "is_deprecated", n => { IsDeprecated = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "no_auth", n => { NoAuth = n.GetBoolValue(); } },
                { "output_parameters", n => { OutputParameters = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsOutputParametersProperty>(global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsOutputParametersProperty.CreateFromDiscriminatorValue); } },
                { "scope_requirements", n => { ScopeRequirements = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsScopeRequirements>(global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsScopeRequirements.CreateFromDiscriminatorValue); } },
                { "scopes", n => { Scopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "toolkit", n => { Toolkit = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsToolkit>(global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsToolkit.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("available_versions", AvailableVersions);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsDeprecated>("deprecated", Deprecated);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("human_description", HumanDescription);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsInputParametersProperty>("input_parameters", InputParameters);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.InstantAccount>("instant", Instant);
            writer.WriteBoolValue("is_deprecated", IsDeprecated);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("no_auth", NoAuth);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsOutputParametersProperty>("output_parameters", OutputParameters);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsScopeRequirements>("scope_requirements", ScopeRequirements);
            writer.WriteCollectionOfPrimitiveValues<string>("scopes", Scopes);
            writer.WriteStringValue("slug", Slug);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Models.ToolDetailsToolkit>("toolkit", Toolkit);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
