// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Codact_failuresPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Arbitrary failure context from the CLI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_ctx? Ctx { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_ctx Ctx { get; set; }
#endif
        /// <summary>Type of codact failure being recorded.</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_failure_type? FailureType { get; set; }
        /// <summary>Optional request identifier associated with the failure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>Arbitrary session payload from the CLI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_session? Session { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_session Session { get; set; }
#endif
        /// <summary>Optional tool metadata when the failure can be tied to a toolkit or concrete tool version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_tool_info? ToolInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_tool_info ToolInfo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody"/> and sets the default values.
        /// </summary>
        public Codact_failuresPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ctx", n => { Ctx = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_ctx>(global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_ctx.CreateFromDiscriminatorValue); } },
                { "failure_type", n => { FailureType = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_failure_type>(); } },
                { "request_id", n => { RequestId = n.GetStringValue(); } },
                { "session", n => { Session = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_session>(global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_session.CreateFromDiscriminatorValue); } },
                { "tool_info", n => { ToolInfo = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_tool_info>(global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_tool_info.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_ctx>("ctx", Ctx);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_failure_type>("failure_type", FailureType);
            writer.WriteStringValue("request_id", RequestId);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_session>("session", Session);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Cli.Codact_failures.Codact_failuresPostRequestBody_tool_info>("tool_info", ToolInfo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
