// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\internal\action_execution\log
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Composio.OpenApiClient.api.v3.internal.action_execution.log.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.Item.LogItemRequestBuilder"/></returns>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.Item.LogItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.Item.LogItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/internal/action_execution/log", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Internal.Action_execution.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/internal/action_execution/log", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
