// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Connected_accountsGetResponse_items_stateMember14_valMember3_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
    }
}
