// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Connected_accountsPostResponse_connectionDataMember2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authScheme property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_authScheme? AuthScheme { get; set; }
        /// <summary>The val property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val? Val { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val Val { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2"/> and sets the default values.
        /// </summary>
        public Connected_accountsPostResponse_connectionDataMember2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authScheme", n => { AuthScheme = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_authScheme>(); } },
                { "val", n => { Val = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val>(global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_authScheme>("authScheme", AuthScheme);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val>("val", Val);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5"/>, <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Connected_accountsPostResponse_connectionDataMember2_val : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1? ConnectedAccountsPostResponseConnectionDataMember2ValMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1 ConnectedAccountsPostResponseConnectionDataMember2ValMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2? ConnectedAccountsPostResponseConnectionDataMember2ValMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2 ConnectedAccountsPostResponseConnectionDataMember2ValMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3? ConnectedAccountsPostResponseConnectionDataMember2ValMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3 ConnectedAccountsPostResponseConnectionDataMember2ValMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4? ConnectedAccountsPostResponseConnectionDataMember2ValMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4 ConnectedAccountsPostResponseConnectionDataMember2ValMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5? ConnectedAccountsPostResponseConnectionDataMember2ValMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5 ConnectedAccountsPostResponseConnectionDataMember2ValMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6? ConnectedAccountsPostResponseConnectionDataMember2ValMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6 ConnectedAccountsPostResponseConnectionDataMember2ValMember6 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2.Connected_accountsPostResponse_connectionDataMember2_val();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember1 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember2 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember3 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember4 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember5 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ConnectedAccountsPostResponseConnectionDataMember2ValMember6 = new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ConnectedAccountsPostResponseConnectionDataMember2ValMember1 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember1.GetFieldDeserializers();
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember2 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember2.GetFieldDeserializers();
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember3 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember3.GetFieldDeserializers();
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember4 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember4.GetFieldDeserializers();
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember5 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember5.GetFieldDeserializers();
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember6 != null)
                {
                    return ConnectedAccountsPostResponseConnectionDataMember2ValMember6.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ConnectedAccountsPostResponseConnectionDataMember2ValMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember1>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember1);
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember2>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember2);
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember3>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember3);
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember4>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember4);
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember5>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember5);
                }
                else if(ConnectedAccountsPostResponseConnectionDataMember2ValMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Connected_accountsPostResponse_connectionDataMember2_valMember6>(null, ConnectedAccountsPostResponseConnectionDataMember2ValMember6);
                }
            }
        }
    }
}
#pragma warning restore CS0618
