// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Auth_configsPostRequestBody_auth_configMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "use_custom_auth")]
        #pragma warning disable CS1591
        Use_custom_auth,
        #pragma warning restore CS1591
    }
}
