// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ISO timestamp when the project was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether this project has been soft-deleted</summary>
        public bool? Deleted { get; set; }
        /// <summary>Email address associated with the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>DEPRECATED: No longer used.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventWebhookUrl { get; set; }
#nullable restore
#else
        public string EventWebhookUrl { get; set; }
#endif
        /// <summary>Unique identifier for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Deprecated: Please refer to webhook_version instead. True indicates if the webhook configuration is using the previous new format (V2). False indicates the oldest format (V1)</summary>
        [Obsolete("")]
        public bool? IsNewWebhook { get; set; }
        /// <summary>ISO timestamp when the project last subscribed to updates</summary>
        public DateTimeOffset? LastSubscribedAt { get; set; }
        /// <summary>Name of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Identifier of the organization that owns this project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>Whether triggers are enabled for this project</summary>
        public bool? TriggersEnabled { get; set; }
        /// <summary>ISO timestamp when the project was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>DEPRECATED: Use GET /api/v3/webhook_subscriptions instead. Legacy project-level webhook secret.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookSecret { get; set; }
#nullable restore
#else
        public string WebhookSecret { get; set; }
#endif
        /// <summary>DEPRECATED: Use GET /api/v3/webhook_subscriptions instead. Legacy project-level webhook URL.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>Payload format version for Pusher real-time events only. For webhook configuration, use GET /api/v3/webhook_subscriptions.</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data_webhook_version? WebhookVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data"/> and sets the default values.
        /// </summary>
        public ListGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "event_webhook_url", n => { EventWebhookUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_new_webhook", n => { IsNewWebhook = n.GetBoolValue(); } },
                { "last_subscribed_at", n => { LastSubscribedAt = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "org_id", n => { OrgId = n.GetStringValue(); } },
                { "triggers_enabled", n => { TriggersEnabled = n.GetBoolValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "webhook_secret", n => { WebhookSecret = n.GetStringValue(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
                { "webhook_version", n => { WebhookVersion = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data_webhook_version>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("event_webhook_url", EventWebhookUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_new_webhook", IsNewWebhook);
            writer.WriteDateTimeOffsetValue("last_subscribed_at", LastSubscribedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("org_id", OrgId);
            writer.WriteBoolValue("triggers_enabled", TriggersEnabled);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("webhook_secret", WebhookSecret);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListGetResponse_data_webhook_version>("webhook_version", WebhookVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
