// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Custom;
using Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate;
using Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item;
using Soenneker.Composio.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\mcp\servers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custom property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Custom.CustomRequestBuilder Custom
        {
            get => new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Custom.CustomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The generate property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GenerateRequestBuilder Generate
        {
            get => new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GenerateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Composio.OpenApiClient.api.v3.mcp.servers.item collection</summary>
        /// <param name="position">The ID of the MCP server</param>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.WithServerItemRequestBuilder"/></returns>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.WithServerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("serverId", position);
                return new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.WithServerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/mcp/servers{?auth_config_ids*,limit*,name*,order_by*,order_direction*,page_no*,toolkits*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/mcp/servers{?auth_config_ids*,limit*,name*,order_by*,order_direction*,page_no*,toolkits*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a paginated list of MCP servers associated with the authenticated project. Results can be filtered by name, toolkit, or authentication configuration ID. MCP servers are used to provide Model Control Protocol integration points for connecting AI assistants to your applications and services.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder.ServersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder.ServersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersGetResponse>(requestInfo, global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new Model Control Protocol (MCP) server instance for the authenticated project. An MCP server provides a connection point for AI assistants to access your applications and services. The server is configured with specific authentication and tool permissions that determine what actions the connected assistants can perform.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostResponse"/></returns>
        /// <param name="body">Request parameters for creating a new MCP server with specific authentication configuration</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Composio.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostResponse?> PostAsync(global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostResponse> PostAsync(global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Composio.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostResponse>(requestInfo, global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a paginated list of MCP servers associated with the authenticated project. Results can be filtered by name, toolkit, or authentication configuration ID. MCP servers are used to provide Model Control Protocol integration points for connecting AI assistants to your applications and services.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder.ServersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder.ServersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new Model Control Protocol (MCP) server instance for the authenticated project. An MCP server provides a connection point for AI assistants to access your applications and services. The server is configured with specific authentication and tool permissions that determine what actions the connected assistants can perform.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request parameters for creating a new MCP server with specific authentication configuration</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.ServersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a paginated list of MCP servers associated with the authenticated project. Results can be filtered by name, toolkit, or authentication configuration ID. MCP servers are used to provide Model Control Protocol integration points for connecting AI assistants to your applications and services.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ServersRequestBuilderGetQueryParameters 
        {
            /// <summary>Comma-separated list of auth config IDs to filter servers by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("auth_config_ids")]
            public string? AuthConfigIds { get; set; }
#nullable restore
#else
            [QueryParameter("auth_config_ids")]
            public string AuthConfigIds { get; set; }
#endif
            /// <summary>Number of items per page (default: 10)</summary>
            [QueryParameter("limit")]
            public double? Limit { get; set; }
            /// <summary>Filter MCP servers by name (case-insensitive partial match)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Field to order results by</summary>
            [QueryParameter("order_by")]
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.GetOrder_byQueryParameterType? OrderBy { get; set; }
            /// <summary>Direction of ordering</summary>
            [QueryParameter("order_direction")]
            public global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.GetOrder_directionQueryParameterType? OrderDirection { get; set; }
            /// <summary>Page number for pagination (1-based)</summary>
            [QueryParameter("page_no")]
            public double? PageNo { get; set; }
            /// <summary>Comma-separated list of toolkit slugs to filter servers by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("toolkits")]
            public string? Toolkits { get; set; }
#nullable restore
#else
            [QueryParameter("toolkits")]
            public string Toolkits { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
