// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RequestPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>ID of the request file. Example: &quot;req_file_9mZn4qR8sXwT&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Object storage upload location. Example: &quot;projects/pr_1a2b3c4d5e6f/requests/slack/SLACK_UPLOAD_FILE/document_9mZn4q.docx&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_metadata Metadata { get; set; }
#endif
        /// <summary>Presigned URL for upload. Example: &quot;https://storage.composio.dev/projects/pr_1a2b3c4d5e6f/requests/slack/document_9mZn4q.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Expires=3600...&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? New_presigned_url { get; set; }
#nullable restore
#else
        public string New_presigned_url { get; set; }
#endif
        /// <summary>[DEPRECATED] Use new_presigned_url instead. Presigned URL for upload. Example: &quot;https://storage.composio.dev/projects/pr_1a2b3c4d5e6f/requests/slack/document_9mZn4q.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Expires=3600...&quot;</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NewPresignedUrl { get; set; }
#nullable restore
#else
        public string NewPresignedUrl { get; set; }
#endif
        /// <summary>[DEPRECATED] Indicates this is a new file that needs to be uploaded</summary>
        [Obsolete("")]
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse"/> and sets the default values.
        /// </summary>
        public RequestPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_metadata>(global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_metadata.CreateFromDiscriminatorValue); } },
                { "newPresignedUrl", n => { NewPresignedUrl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_type>(); } },
                { "new_presigned_url", n => { New_presigned_url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("key", Key);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_metadata>("metadata", Metadata);
            writer.WriteStringValue("new_presigned_url", New_presigned_url);
            writer.WriteStringValue("newPresignedUrl", NewPresignedUrl);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Files.Upload.Request.RequestPostResponse_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
