// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances
{
    /// <summary>
    /// Paginated list of instances for an MCP server
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstancesGetResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current page number being returned</summary>
        public double? CurrentPage { get; set; }
        /// <summary>List of instance objects associated with this MCP server for the current page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse_instances>? Instances { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse_instances> Instances { get; set; }
#endif
        /// <summary>UUID of the MCP server</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>Name of the MCP server</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerName { get; set; }
#nullable restore
#else
        public string ServerName { get; set; }
#endif
        /// <summary>Total number of pages in the paginated response</summary>
        public double? TotalPages { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse"/> and sets the default values.
        /// </summary>
        public InstancesGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_page", n => { CurrentPage = n.GetDoubleValue(); } },
                { "instances", n => { Instances = n.GetCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse_instances>(global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse_instances.CreateFromDiscriminatorValue)?.AsList(); } },
                { "server_id", n => { ServerId = n.GetStringValue(); } },
                { "server_name", n => { ServerName = n.GetStringValue(); } },
                { "total_pages", n => { TotalPages = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("current_page", CurrentPage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Item.Instances.InstancesGetResponse_instances>("instances", Instances);
            writer.WriteStringValue("server_id", ServerId);
            writer.WriteStringValue("server_name", ServerName);
            writer.WriteDoubleValue("total_pages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
