// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Files.List
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListGetResponse_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Name of the original file. Example: &quot;document.docx&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>MD5 hash of the file for integrity verification. Example: &quot;d41d8cd98f00b204e9800998ecf8427e&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Md5 { get; set; }
#nullable restore
#else
        public string Md5 { get; set; }
#endif
        /// <summary>Mime type of the original file. Example: &quot;application/vnd.openxmlformats-officedocument.wordprocessingml.document&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mimetype { get; set; }
#nullable restore
#else
        public string Mimetype { get; set; }
#endif
        /// <summary>Slug of the app where this file belongs to. Example: &quot;file-converter&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolkitSlug { get; set; }
#nullable restore
#else
        public string ToolkitSlug { get; set; }
#endif
        /// <summary>Slug of the action where this file belongs to. Example: &quot;convert-to-pdf&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToolSlug { get; set; }
#nullable restore
#else
        public string ToolSlug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Files.List.ListGetResponse_items"/> and sets the default values.
        /// </summary>
        public ListGetResponse_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Files.List.ListGetResponse_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Files.List.ListGetResponse_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Files.List.ListGetResponse_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "md5", n => { Md5 = n.GetStringValue(); } },
                { "mimetype", n => { Mimetype = n.GetStringValue(); } },
                { "tool_slug", n => { ToolSlug = n.GetStringValue(); } },
                { "toolkit_slug", n => { ToolkitSlug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("filename", Filename);
            writer.WriteStringValue("md5", Md5);
            writer.WriteStringValue("mimetype", Mimetype);
            writer.WriteStringValue("toolkit_slug", ToolkitSlug);
            writer.WriteStringValue("tool_slug", ToolSlug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
