// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithSession_PatchRequestBody_manage_connections : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The URL to redirect to after a user completes authentication for a connected account. This allows you to handle the auth callback in your own application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>Whether to enable the connection manager for automatic connection handling. If true, we will provide a tool your agent can use to initiate connections to toolkits if it doesnt exist. If set to false, then you have to manage connections manually.</summary>
        public bool? Enable { get; set; }
        /// <summary>Enable the &quot;remove&quot; action in COMPOSIO_MANAGE_CONNECTIONS to allow deleting connected accounts. Default true.</summary>
        public bool? EnableConnectionRemoval { get; set; }
        /// <summary>When true, the COMPOSIO_WAIT_FOR_CONNECTIONS tool is available for agents to poll connection status after sharing auth URLs. Default is false (disabled). May not work reliably with GPT models.</summary>
        public bool? EnableWaitForConnections { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item.WithSession_PatchRequestBody_manage_connections"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item.WithSession_PatchRequestBody_manage_connections CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item.WithSession_PatchRequestBody_manage_connections();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callback_url", n => { CallbackUrl = n.GetStringValue(); } },
                { "enable", n => { Enable = n.GetBoolValue(); } },
                { "enable_connection_removal", n => { EnableConnectionRemoval = n.GetBoolValue(); } },
                { "enable_wait_for_connections", n => { EnableWaitForConnections = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("callback_url", CallbackUrl);
            writer.WriteBoolValue("enable", Enable);
            writer.WriteBoolValue("enable_connection_removal", EnableConnectionRemoval);
            writer.WriteBoolValue("enable_wait_for_connections", EnableWaitForConnections);
        }
    }
}
#pragma warning restore CS0618
