// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Tool_router.Session.Item
{
    /// <summary>The type of the MCP server. Can be http</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithSession_PatchResponse_mcp_type
    {
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
    }
}
