// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Internal.Trigger.Logs
{
    /// <summary>Filter logs by their status level</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogsPostRequestBody_status
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
