// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Link
{
    /// <summary>
    /// Access control for SHARED connections. Visible only to the connection creator and project/org API key callers; non-creator cookie callers receive the response without this block.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkPostResponse_experimental_acl_config_for_shared : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allow_all_users property</summary>
        public bool? AllowAllUsers { get; set; }
        /// <summary>The allowed_user_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedUserIds { get; set; }
#nullable restore
#else
        public List<string> AllowedUserIds { get; set; }
#endif
        /// <summary>The not_allowed_user_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NotAllowedUserIds { get; set; }
#nullable restore
#else
        public List<string> NotAllowedUserIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Link.LinkPostResponse_experimental_acl_config_for_shared"/> and sets the default values.
        /// </summary>
        public LinkPostResponse_experimental_acl_config_for_shared()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Link.LinkPostResponse_experimental_acl_config_for_shared"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Link.LinkPostResponse_experimental_acl_config_for_shared CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Link.LinkPostResponse_experimental_acl_config_for_shared();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_all_users", n => { AllowAllUsers = n.GetBoolValue(); } },
                { "allowed_user_ids", n => { AllowedUserIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "not_allowed_user_ids", n => { NotAllowedUserIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_all_users", AllowAllUsers);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_user_ids", AllowedUserIds);
            writer.WriteCollectionOfPrimitiveValues<string>("not_allowed_user_ids", NotAllowedUserIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
