// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTool_slugPostRequestBody_custom_auth_params_parameters : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The location of the parameter. Can be &apos;query&apos; or &apos;header&apos;.</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters_in? In { get; set; }
        /// <summary>The name of the parameter. For example, &apos;x-api-key&apos;, &apos;Content-Type&apos;, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The value of the parameter. For example, &apos;1234567890&apos;, &apos;application/json&apos;, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters"/> and sets the default values.
        /// </summary>
        public WithTool_slugPostRequestBody_custom_auth_params_parameters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "in", n => { In = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters_in>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value>(global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters_in>("in", In);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTool_slugPostRequestBody_custom_auth_params_parameters_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Composio.OpenApiClient.Api.V31.Tools.Execute.Item.WithTool_slugPostRequestBody_custom_auth_params_parameters.WithTool_slugPostRequestBody_custom_auth_params_parameters_value();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
