// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.Item;
using Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List;
using Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.New;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\org\owner\project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The new property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.New.NewRequestBuilder New
        {
            get => new global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.New.NewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Composio.OpenApiClient.api.v3.org.owner.project.item collection</summary>
        /// <param name="position">Unique identifier (Nano ID) of the project to retrieve</param>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.Item.WithNano_ItemRequestBuilder"/></returns>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.Item.WithNano_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("nano_id", position);
                return new global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.Item.WithNano_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/org/owner/project", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Org.Owner.Project.ProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/org/owner/project", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
