// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Item;
using Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Proxy;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3\tools\execute
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExecuteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The proxy property</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Proxy.ProxyRequestBuilder Proxy
        {
            get => new global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Proxy.ProxyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Composio.OpenApiClient.api.v3.tools.execute.item collection</summary>
        /// <param name="position">The tool slug to execute</param>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Item.WithTool_slugItemRequestBuilder"/></returns>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Item.WithTool_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tool_slug", position);
                return new global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.Item.WithTool_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.ExecuteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecuteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/tools/execute", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Tools.Execute.ExecuteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExecuteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3/tools/execute", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
