// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info
{
    /// <summary>
    /// Details of the current active project (null if accessing with org-level credentials)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfoGetResponse_project : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Internal auto-incrementing ID for the project</summary>
        public double? AutoId { get; set; }
        /// <summary>Date and time when the project was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Flag indicating if the project has been deleted</summary>
        public bool? Deleted { get; set; }
        /// <summary>Email address used for project notifications</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Endpoint URL for event webhook notifications</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventWebhookUrl { get; set; }
#nullable restore
#else
        public string EventWebhookUrl { get; set; }
#endif
        /// <summary>UUID identifier for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Deprecated: Please refer to webhook_version instead. True indicates if the webhook configuration is using the previous new format (V2). False indicates the oldest format (V1)</summary>
        [Obsolete("")]
        public bool? IsNewWebhook { get; set; }
        /// <summary>Date and time when the project last subscribed to updates</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSubscribedAt { get; set; }
#nullable restore
#else
        public string LastSubscribedAt { get; set; }
#endif
        /// <summary>User-defined name for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Short, URL-friendly unique identifier for the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NanoId { get; set; }
#nullable restore
#else
        public string NanoId { get; set; }
#endif
        /// <summary>Organization details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_org? Org { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_org Org { get; set; }
#endif
        /// <summary>Organization UUID that this project belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>Flag indicating if triggers are enabled for this project</summary>
        public bool? TriggersEnabled { get; set; }
        /// <summary>Date and time when the project was last modified</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>Secret used to verify webhook signatures</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookSecret { get; set; }
#nullable restore
#else
        public string WebhookSecret { get; set; }
#endif
        /// <summary>Endpoint URL for trigger webhook notifications</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookUrl { get; set; }
#nullable restore
#else
        public string WebhookUrl { get; set; }
#endif
        /// <summary>Version of the webhook configuration</summary>
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_webhook_version? WebhookVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project"/> and sets the default values.
        /// </summary>
        public InfoGetResponse_project()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auto_id", n => { AutoId = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "event_webhook_url", n => { EventWebhookUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_new_webhook", n => { IsNewWebhook = n.GetBoolValue(); } },
                { "last_subscribed_at", n => { LastSubscribedAt = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nano_id", n => { NanoId = n.GetStringValue(); } },
                { "org", n => { Org = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_org>(global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_org.CreateFromDiscriminatorValue); } },
                { "org_id", n => { OrgId = n.GetStringValue(); } },
                { "triggers_enabled", n => { TriggersEnabled = n.GetBoolValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "webhook_secret", n => { WebhookSecret = n.GetStringValue(); } },
                { "webhook_url", n => { WebhookUrl = n.GetStringValue(); } },
                { "webhook_version", n => { WebhookVersion = n.GetEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_webhook_version>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("auto_id", AutoId);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("event_webhook_url", EventWebhookUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_new_webhook", IsNewWebhook);
            writer.WriteStringValue("last_subscribed_at", LastSubscribedAt);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("nano_id", NanoId);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_org>("org", Org);
            writer.WriteStringValue("org_id", OrgId);
            writer.WriteBoolValue("triggers_enabled", TriggersEnabled);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("webhook_secret", WebhookSecret);
            writer.WriteStringValue("webhook_url", WebhookUrl);
            writer.WriteEnumValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth.Session.Info.InfoGetResponse_project_webhook_version>("webhook_version", WebhookVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
