// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Webhook_subscriptions.Event_types
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Event_typesGetResponse_items_supported_versions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "V1")]
        #pragma warning disable CS1591
        V1,
        #pragma warning restore CS1591
        [EnumMember(Value = "V2")]
        #pragma warning disable CS1591
        V2,
        #pragma warning restore CS1591
        [EnumMember(Value = "V3")]
        #pragma warning disable CS1591
        V3,
        #pragma warning restore CS1591
    }
}
