// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithNanoPatchRequestBodyMember1_credentials : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The scopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes? Scopes { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes Scopes { get; set; }
#endif
        /// <summary>The user_scopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes? UserScopes { get; set; }
#nullable restore
#else
        public global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes UserScopes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials"/> and sets the default values.
        /// </summary>
        public WithNanoPatchRequestBodyMember1_credentials()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "scopes", n => { Scopes = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes>(global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes.CreateFromDiscriminatorValue); } },
                { "user_scopes", n => { UserScopes = n.GetObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes>(global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes>("scopes", Scopes);
            writer.WriteObjectValue<global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes>("user_scopes", UserScopes);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithNanoPatchRequestBodyMember1_credentials_scopes : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? WithNanoPatchRequestBodyMember1CredentialsScopesString { get; set; }
#nullable restore
#else
            public string WithNanoPatchRequestBodyMember1CredentialsScopesString { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_scopes();
                if(parseNode.GetStringValue() is string withNanoPatchRequestBodyMember1CredentialsScopesStringValue)
                {
                    result.WithNanoPatchRequestBodyMember1CredentialsScopesString = withNanoPatchRequestBodyMember1CredentialsScopesStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithNanoPatchRequestBodyMember1CredentialsScopesString != null)
                {
                    writer.WriteStringValue(null, WithNanoPatchRequestBodyMember1CredentialsScopesString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithNanoPatchRequestBodyMember1_credentials_user_scopes : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? WithNanoPatchRequestBodyMember1CredentialsUserScopesString { get; set; }
#nullable restore
#else
            public string WithNanoPatchRequestBodyMember1CredentialsUserScopesString { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Composio.OpenApiClient.Api.V3.Auth_configs.Item.WithNanoPatchRequestBodyMember1_credentials.WithNanoPatchRequestBodyMember1_credentials_user_scopes();
                if(parseNode.GetStringValue() is string withNanoPatchRequestBodyMember1CredentialsUserScopesStringValue)
                {
                    result.WithNanoPatchRequestBodyMember1CredentialsUserScopesString = withNanoPatchRequestBodyMember1CredentialsUserScopesStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithNanoPatchRequestBodyMember1CredentialsUserScopesString != null)
                {
                    writer.WriteStringValue(null, WithNanoPatchRequestBodyMember1CredentialsUserScopesString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
