// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Internal.Trigger.Log.Item
{
    /// <summary>Log entity type (trigger or action)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogGetResponse_log_type
    {
        [EnumMember(Value = "trigger")]
        #pragma warning disable CS1591
        Trigger,
        #pragma warning restore CS1591
        [EnumMember(Value = "action")]
        #pragma warning disable CS1591
        Action,
        #pragma warning restore CS1591
    }
}
