// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate
{
    /// <summary>
    /// Request parameters for generating an MCP URL
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GeneratePostRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of connected account identifiers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ConnectedAccountIds { get; set; }
#nullable restore
#else
        public List<string> ConnectedAccountIds { get; set; }
#endif
        /// <summary>Flag indicating if Composio manages authentication</summary>
        public bool? ManagedAuthByComposio { get; set; }
        /// <summary>Unique identifier of the MCP server to generate URL for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? McpServerId { get; set; }
#nullable restore
#else
        public string McpServerId { get; set; }
#endif
        /// <summary>List of user identifiers for whom the URL is generated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UserIds { get; set; }
#nullable restore
#else
        public List<string> UserIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GeneratePostRequestBody"/> and sets the default values.
        /// </summary>
        public GeneratePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GeneratePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GeneratePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Mcp.Servers.Generate.GeneratePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connected_account_ids", n => { ConnectedAccountIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "managed_auth_by_composio", n => { ManagedAuthByComposio = n.GetBoolValue(); } },
                { "mcp_server_id", n => { McpServerId = n.GetStringValue(); } },
                { "user_ids", n => { UserIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("connected_account_ids", ConnectedAccountIds);
            writer.WriteBoolValue("managed_auth_by_composio", ManagedAuthByComposio);
            writer.WriteStringValue("mcp_server_id", McpServerId);
            writer.WriteCollectionOfPrimitiveValues<string>("user_ids", UserIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
