// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi
{
    /// <summary>Determines how toolkits should be sorted in the response</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MultiPostRequestBody_sort_by
    {
        [EnumMember(Value = "usage")]
        #pragma warning disable CS1591
        Usage,
        #pragma warning restore CS1591
        [EnumMember(Value = "alphabetically")]
        #pragma warning disable CS1591
        Alphabetically,
        #pragma warning restore CS1591
    }
}
