// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi
{
    /// <summary>
    /// Additional metadata about the toolkit
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MultiPostResponse_items_meta : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Link to the toolkit&apos;s main application or service website</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppUrl { get; set; }
#nullable restore
#else
        public string AppUrl { get; set; }
#endif
        /// <summary>List of categories associated with this toolkit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta_categories>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta_categories> Categories { get; set; }
#endif
        /// <summary>Creation date and time of the toolkit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Human-readable description explaining the toolkit&apos;s purpose and functionality</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Image URL for the toolkit&apos;s branding</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logo { get; set; }
#nullable restore
#else
        public string Logo { get; set; }
#endif
        /// <summary>Count of available tools in this toolkit</summary>
        public double? ToolsCount { get; set; }
        /// <summary>Count of available triggers in this toolkit</summary>
        public double? TriggersCount { get; set; }
        /// <summary>Last modification date and time of the toolkit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>Version of the toolkit</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta"/> and sets the default values.
        /// </summary>
        public MultiPostResponse_items_meta()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_url", n => { AppUrl = n.GetStringValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta_categories>(global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta_categories.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "logo", n => { Logo = n.GetStringValue(); } },
                { "tools_count", n => { ToolsCount = n.GetDoubleValue(); } },
                { "triggers_count", n => { TriggersCount = n.GetDoubleValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_url", AppUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Composio.OpenApiClient.Api.V3.Toolkits.Multi.MultiPostResponse_items_meta_categories>("categories", Categories);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("logo", Logo);
            writer.WriteDoubleValue("tools_count", ToolsCount);
            writer.WriteDoubleValue("triggers_count", TriggersCount);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
