// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Connected_accounts.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NanoGetResponse_stateMember13_authScheme
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DCR_OAUTH")]
        #pragma warning disable CS1591
        DCR_OAUTH,
        #pragma warning restore CS1591
    }
}
