// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Composio.OpenApiClient.Api.V3.Triggers_types
{
    /// <summary>The trigger mechanism - either webhook (event-based) or poll (scheduled check)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Triggers_typesGetResponse_items_type
    {
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
        [EnumMember(Value = "poll")]
        #pragma warning disable CS1591
        Poll,
        #pragma warning restore CS1591
    }
}
